### ISSUE TITLE
Using variable using docker compose with portainer stacks & IPV6 update

### ISSUE THREAD

**Issue by smailpouri** [joweisberg/docker-dynamic-dns#11]
When using ${HOSTNAME} for example it won't parse the info properly, I tried with duckdns or noip

```
version: '3.5'
services:
  dynamic-dns:
    container_name: ${CONTAINER}
    hostname: ${CONTAINER}
    image: joweisberg/dynamic-dns:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
      - SERVICE=${SERVICE}
      - USER=${USER}
      - PASSWORD=${PASSWORD}
      - HOSTNAME=${HOSTNAME}
    healthcheck:
      test: /usr/bin/healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
```

```
CONTAINER=ddns-duckdns
SERVICE=duckdns
USER=username@myemail.com
PASSWORD=1111111111111
HOSTNAME=myhost.duckdns.org
```

And this below does not seem to do anything either.
`UPDATEIPV6=1`
